# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("calculator.proto", :syntax => :proto3) do
    add_message "calculator.Input" do
      optional :first_value, :float, 1
      optional :second_value, :float, 2
    end
    add_message "calculator.Output" do
      optional :value, :float, 1
    end
  end
end

module Calculator
  Input = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("calculator.Input").msgclass
  Output = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("calculator.Output").msgclass
end
